# Generated by Django 5.1.2 on 2024-10-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_specialization_doctor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
